Change name of demo section

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,10 +2,10 @@
 
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
-# if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
-#     echo "You can't commit directly to $branch branch Einstein..."
-#     exit 1
-# fi
+if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
+    echo "You can't commit directly to $branch branch Einstein..."
+    exit 1
+fi
 
 just format_package_jsons
 
